development:
  adapter: postgresql
  encoding: unicode
  database: weather_ajax_development
  pool: 5
  username: ericmooney
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: weather_ajax_test
  pool: 5
  username: ericmooney
  password:
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: weather_ajax_production
  pool: 5
  username: ericmooney
  password:
  host: localhost
